-------------------------------------------------------------------------------------------------
-- TAGS_STRUCTURE
-------------------------------------------------------------------------------------------------
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

DECLARE @DB_NAME VARCHAR(128) = 'VideoHosting';
DECLARE @DB_NAME_CURRENT VARCHAR(128) = NULL;
DECLARE @IS_COMMIT BIT = 0;

BEGIN TRAN
PRINT N'➕ JOB IS STARTED';

SET @DB_NAME_CURRENT = (SELECT DB_NAME());
IF NOT (@DB_NAME_CURRENT = @DB_NAME) BEGIN
	PRINT N'➕ CURRENT DB IS NOT CORRECT: ' + @DB_NAME_CURRENT;
END ELSE BEGIN
    PRINT N'➕ CURRENT DB IS CORRECT: ' + @DB_NAME_CURRENT;
    IF EXISTS (SELECT 1 FROM [sys].[tables] WHERE [name] = N'TAGS') BEGIN
	    PRINT N'❌ TABLE [TAGS] IS ALREADY EXISTS';
    END ELSE BEGIN
	    PRINT N'➕ TABLE [TAGS] IS NOT EXISTS AND WILL BE CREATED';
        CREATE TABLE [dbo].[TAGS] (
			[UID] [UNIQUEIDENTIFIER] NOT NULL,
			[TITLE] [NVARCHAR](16) NOT NULL,
		);
        PRINT N'➕ TABLE [TAGS] WAS CREATED';
    END;
    -- PRIMARY KEY
    IF NOT EXISTS (SELECT 1 FROM [INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] 
    WHERE [CONSTRAINT_TYPE] = 'PRIMARY KEY' AND [TABLE_NAME] = N'TAGS') BEGIN
        ALTER TABLE [dbo].[TAGS] ADD CONSTRAINT [PK_TAGS_UID] PRIMARY KEY CLUSTERED ([UID] ASC)
            PRINT N'➕ PRIMARY KEY [PK_TAGS_UID] WAS CREATED';
    END;
    -- UNIQUE
    IF NOT EXISTS (SELECT 1 FROM [INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] 
    WHERE [CONSTRAINT_NAME] = 'UQ_TAGS_TITLE' AND [TABLE_NAME] = N'TAGS') BEGIN
        ALTER TABLE [dbo].[TAGS] ADD CONSTRAINT [UQ_TAGS_TITLE] UNIQUE([TITLE])
        PRINT N'➕ UNIQUE KEY [UQ_TAGS_NAME] WAS CREATED';
    END;
END;
IF (@IS_COMMIT = 1) BEGIN
	COMMIT TRAN
	PRINT N'➕ INSERT IS COMMITTED'
END ELSE BEGIN
    ROLLBACK TRAN
	PRINT N'❌ INSERT IS ROLL-BACKED'
END;
--------------------------------------------------------------------------------------------------