-------------------------------------------------------------------------------------------------
-- FK_VIDEO_PLAYLISTS_INSERT
-------------------------------------------------------------------------------------------------
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

DECLARE @IS_COMMIT BIT = 1;
-------------------------------------------------------------------------------------------------
USE VideoHosting;

BEGIN TRAN
PRINT N'➕ JOB IS STARTED';

IF NOT EXISTS (SELECT 1 FROM [sys].[tables] WHERE [name] = N'FK_VIDEO_PLAYLISTS') BEGIN
	PRINT N'❌ TABLE [FK_VIDEO_PLAYLISTS] WAS NOT FOUND';
END ELSE BEGIN
    -- CREATE VARIABLES
    DECLARE @PLAYLIST NVARCHAR(32);
    DECLARE @VIDEO NVARCHAR(100);
    
    DECLARE @PLAYLIST_UID UNIQUEIDENTIFIER;
    DECLARE @VIDEO_UID UNIQUEIDENTIFIER;

    -- CREATE TMP TABLES
    BEGIN 
        DROP TABLE IF EXISTS #CSV;
        CREATE TABLE #CSV (
            [PLAYLIST] NVARCHAR(32) NOT NULL,
            [VIDEO] NVARCHAR(100) NOT NULL,
        );
        BULK INSERT #CSV FROM '/DataCsv/fk_video_playlists.csv'
        WITH (
	        FIRSTROW = 2,
	        FIELDTERMINATOR = ';',
	        ROWTERMINATOR = '\n',
            DATAFILETYPE = 'WideChar'
        );
        PRINT N'➕ CREATE TEMP TABLES IS SUCCESS'
    END;

    -- INSERT TABLE
    BEGIN
        DECLARE CUR CURSOR FOR SELECT [PLAYLIST], [VIDEO] FROM #CSV;
        OPEN CUR;
        FETCH NEXT FROM CUR INTO @PLAYLIST, @VIDEO;
        WHILE @@FETCH_STATUS = 0 BEGIN
            SET @PLAYLIST_UID = (SELECT [UID] FROM [PLAYLISTS] WHERE [TITLE] = @PLAYLIST);
            SET @VIDEO_UID = (SELECT [UID] FROM [VIDEOS] WHERE [TITLE] = @VIDEO);

            MERGE INTO [FK_VIDEO_PLAYLISTS] AS [VIDEO_PLAYLIST_FK] 
                USING (VALUES (@PLAYLIST_UID, @VIDEO_UID)) AS [NEW_VIDEO_PLAYLIST_FK] ([PLAYLIST_UID], [VIDEO_UID])
                ON [VIDEO_PLAYLIST_FK].[VIDEO_UID] = @VIDEO_UID AND [VIDEO_PLAYLIST_FK].[PLAYLIST_UID] = @PLAYLIST_UID
                WHEN NOT MATCHED THEN
                    INSERT ([VIDEO_UID], [PLAYLIST_UID]) VALUES (@VIDEO_UID, @PLAYLIST_UID);
            FETCH NEXT FROM CUR INTO @PLAYLIST, @VIDEO;
        END;
        CLOSE CUR;
        DEALLOCATE CUR;

        PRINT N'➕ INSERT IS SUCCESS'
    END;
    DROP TABLE IF EXISTS #CSV;
    PRINT N'➕ DROP TEMP TABLES IS SUCCESS'
END;


IF (@IS_COMMIT = 1) BEGIN
    COMMIT TRAN
    PRINT N'➕ INSERT IS COMMITTED'
END ELSE BEGIN
    ROLLBACK TRAN
    PRINT N'❌ INSERT IS ROLL-BACKED'
END;
