-----------------------------------------------------------------------------------------------
-- SUBSCRIPTIONS_STRUCTURE
-------------------------------------------------------------------------------------------------
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

DECLARE @IS_COMMIT BIT = 0;
-------------------------------------------------------------------------------------------------
USE VideoHosting;

BEGIN TRAN
PRINT N'➕ JOB IS STARTED';

IF EXISTS (SELECT * FROM [sys].[tables] WHERE [name] = N'SUBSCRIPTIONS') BEGIN
	PRINT N'❌ TABLE [SUBSCRIPTIONS] IS ALREADY EXISTS';
END ELSE BEGIN
	PRINT N'➕ TABLE [SUBSCRIPTIONS] IS NOT EXISTS AND WILL BE CREATED';
    CREATE TABLE [SUBSCRIPTIONS] (
		[UID] UNIQUEIDENTIFIER NOT NULL,
        [TO_USER_UID] UNIQUEIDENTIFIER NOT NULL, 
        [FROM_USER_UID] UNIQUEIDENTIFIER NOT NULL,
        [CREATED_DT] DATETIME NOT NULL,
	);
    PRINT N'➕ TABLE [SUBSCRIPTIONS] WAS CREATED';
END;

-- PRIMARY KEY
IF NOT EXISTS (SELECT 1 FROM [INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE [CONSTRAINT_TYPE] = 'PRIMARY KEY' AND [TABLE_NAME] = N'SUBSCRIPTIONS') BEGIN
    ALTER TABLE [SUBSCRIPTIONS] ADD CONSTRAINT [PK_SUBSCRIPTIONS_UID] PRIMARY KEY CLUSTERED ([UID] ASC)
        PRINT N'➕ PRIMARY KEY [PK_SUBSCRIPTIONS_UID] WAS CREATED';
END;

-- FOREIGN KEY
IF NOT EXISTS (SELECT 1 FROM [INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE [CONSTRAINT_NAME] = 'FK_SUBSCRIPTIONS_TO_USER_UID') BEGIN
	ALTER TABLE [SUBSCRIPTIONS] ADD CONSTRAINT [FK_SUBSCRIPTIONS_TO_USER_UID] 
        FOREIGN KEY([TO_USER_UID]) REFERENCES [USERS] ([UID]);
	PRINT N'➕ FOREIGN KEY [FK_SUBSCRIPTIONS_TO_USER_UID] WAS CREATED';
END;
IF NOT EXISTS (SELECT 1 FROM [INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE [CONSTRAINT_NAME] = 'FK_SUBSCRIPTIONS_FROM_USER_UID') BEGIN
	ALTER TABLE [SUBSCRIPTIONS] ADD CONSTRAINT [FK_SUBSCRIPTIONS_FROM_USER_UID] 
        FOREIGN KEY([FROM_USER_UID]) REFERENCES [USERS] ([UID]);
	PRINT N'➕ FOREIGN KEY [FK_SUBSCRIPTIONS_FROM_USER_UID_UID] WAS CREATED';
END;

-- UNIQUE
IF NOT EXISTS (SELECT 1 FROM [INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE [CONSTRAINT_NAME] = 'UQ_SUBSCRIPTIONS_USERS_UID' AND [TABLE_NAME] = N'SUBSCRIPTIONS') BEGIN
    ALTER TABLE [SUBSCRIPTIONS] ADD CONSTRAINT [UQ_SUBSCRIPTIONS_USERS_UID] UNIQUE([TO_USER_UID], [FROM_USER_UID])
    PRINT N'➕ UNIQUE KEY [UQ_SUBSCRIPTIONS_USERS_UID] WAS CREATED';
END;

-- DEFAULT
IF NOT EXISTS (SELECT 1 FROM [SYS].[DEFAULT_CONSTRAINTS] WHERE [NAME] = 'DF_SUBSCRIPTIONS_UID') BEGIN
	ALTER TABLE [SUBSCRIPTIONS] ADD CONSTRAINT [DF_SUBSCRIPTIONS_UID] DEFAULT (NEWID()) FOR [UID];
	PRINT N'➕ DEFAULT KEY [DF_SUBSCRIPTIONS_UID] WAS CREATED';
END;
IF NOT EXISTS (SELECT 1 FROM [SYS].[DEFAULT_CONSTRAINTS] WHERE [NAME] = 'DF_SUBSCRIPTIONS_CREATED_DT') BEGIN
    ALTER TABLE [SUBSCRIPTIONS] ADD CONSTRAINT [DF_SUBSCRIPTIONS_CREATED_DT] DEFAULT (GETDATE()) FOR [CREATED_DT];
    PRINT N'➕ DEFAULT KEY [DF_SUBSCRIPTIONS_CREATED_DT] WAS CREATED';
END;

IF (@IS_COMMIT = 1) BEGIN
	COMMIT TRAN
	PRINT N'➕ STRUCTURE IS COMMITTED'
END ELSE BEGIN
    ROLLBACK TRAN
	PRINT N'❌ STRUCTURE IS ROLL-BACKED'
END;
